/*
  Preguntas difíciles sobre el trabajo, con respuestas argumentadas y su respaldo en la tesis.
  Salen de las preguntas que una comisión exigente haría al leer la tesis.

  Campos
  id      identificador estable, se usa en el enlace preguntas.html#p-<id>
  tema    clave de TEMAS_FAQ
  nivel   general, tecnica o exigente
  q       la pregunta
  r       la respuesta, en párrafos separados por \n\n
  donde   dónde está el respaldo en la tesis
  ver     enlace a la explicación en la guía
*/
window.TEMAS_FAQ = [
  { id: "objetivos", t: "Objetivos y alcance", cap: "resultados.html" },
  { id: "control", t: "Control de las ruedas", cap: "control.html" },
  { id: "odometria", t: "Odometría y ensayos", cap: "movimiento.html" },
  { id: "mapeo", t: "Mapeo y SLAM", cap: "mapeo.html" },
  { id: "navegacion", t: "Navegación", cap: "navegacion.html" },
  { id: "exploracion", t: "Exploración por fronteras", cap: "exploracion.html" },
  { id: "gemelo", t: "Gemelo digital y simulación", cap: "gemelo.html" },
  { id: "decisiones", t: "Decisiones de diseño", cap: "problema.html" },
  { id: "publico", t: "Para todo público", cap: "index.html" }
];

window.PREGUNTAS = [
  /* ── Objetivos y alcance ── */
  { id: "objetivo-general", tema: "objetivos", nivel: "general",
    q: "¿Se cumplió el objetivo general, y cómo se sabe que el robot realmente se movió?",
    r: "Para mapear y explorar, sí. En cinco de las seis ejecuciones el robot construyó un mapa 2D y terminó solo, cuando el explorador ya no encontró fronteras.\n\nQue se movió se sabe porque el mapa creció en cada corrida, con coberturas de entre 53,4 y 82,9 %, y eso exige que el láser vea geometría nueva desde otras posiciones. Las metas generadas no prueban movimiento, porque en la corrida excluida hubo 14 metas y el robot no se movió.\n\nLa navegación funcionó de punta a punta, pero sin un indicador cuantitativo propio. Por eso OE1 y OE4 están cumplidos y OE2 y OE3 cumplidos en parte.",
    donde: "Conclusiones, Sec. 5.4, Tabla 5.5, Anexo 7", ver: "resultados.html#objetivos" },
  { id: "una-de-sesenta", tema: "objetivos", nivel: "exigente",
    q: "Si de 60 destinos el robot llegó a uno, ¿cómo se puede afirmar que sabe ir a donde se le pide?",
    r: "Esa cifra no mide si el robot llega. El explorador vuelve a elegir destino cada 3,3 s y manda el nuevo sin cancelar el anterior, y Nav2, en la versión usada, cierra el anterior como abortado.\n\nRevisando cada meta por su identificador, 53 de los 54 abortos fueron reemplazos. Además, el tiempo mediano que cada meta estuvo activa fue 3,3 s, igual al período del explorador.\n\nLo que muestra que el robot va hacia donde se le manda es que, en cinco de seis corridas, el mapa creció hasta que no quedaron fronteras. Medirlo con destinos fijos es el trabajo futuro 1.",
    donde: "Sec. 5.4, Tabla A7.1, Anexo 8.4", ver: "exploracion.html#abortadas" },
  { id: "metas-fijas", tema: "objetivos", nivel: "exigente",
    q: "Si el script de metas fijas estaba preparado, ¿por qué no se ejecutó ese ensayo?",
    r: "Porque quedó fuera del alcance declarado. Lo comprometido en el objetivo general es navegar hacia destinos generados por el explorador, y así se evaluó.\n\nUn protocolo con metas fijas exige un mapa guardado, AMCL activo y puntos medidos en el recinto, y esas condiciones no se configuraron. Además, el script preparado no tiene registros de salida, no mide el error de posición final y sus poses objetivo solo existen para el mundo simulado. Ejecutarlo es el trabajo futuro 1.",
    donde: "Alcances y limitaciones, Sec. 4.5.2, Sec. 5.4, Anexo 8.3", ver: "navegacion.html#evaluacion" },
  { id: "todo-el-recinto", tema: "objetivos", nivel: "tecnica",
    q: "Si la superficie del recinto no se midió aparte del mapa, ¿cómo se sabe que el robot lo exploró todo?",
    r: "No se puede afirmar que exploró todo el recinto. Hay dos evidencias de que llegó a todo el espacio alcanzable. Las cinco corridas válidas terminaron solas porque no quedaban fronteras, y el área libre fue casi igual en las cinco, entre 3,478 y 3,540 m², con una desviación de 0,03 m².\n\nEl índice de cobertura se calcula sobre la imagen del mapa y no sobre la sala, por eso varía tanto. Medir el recinto aparte del mapa queda como mejora pendiente.",
    donde: "Sec. 5.3, Tabla 5.4, Limitaciones", ver: "mapeo.html#resultados" },

  /* ── Control ── */
  { id: "sin-derivativa", tema: "control", nivel: "exigente",
    q: "El código tiene una ganancia llamada Kd cercana a 20. ¿Por qué se dice que la ley no tiene acción derivativa?",
    r: "Porque el firmware no calcula la salida completa en cada ciclo. Calcula un aumento y lo suma a la salida anterior, y esa suma hace que cada término suba un orden de integración.\n\nKp multiplica el error y, al acumularse, actúa como integral. Kd multiplica el cambio de la medición y, al acumularse, actúa como proporcional sobre la medición. Ki se acumula dos veces y actúa como segunda integración. Sin Ki, la ley coincide con un PI incremental como el que describen Åström y Hägglund.\n\nAsí opera la rueda derecha, cuyo estado integral entero queda siempre en cero. Por eso el objetivo pedía un PID, el resultado es un PI, y el OE2 queda parcial.",
    donde: "Sec. 4.4.3, Ec. 4.1, Anexos 4.4 y 4.5, Sec. 5.2", ver: "control.html#hallazgo" },
  { id: "por-que-no-reemplazo", tema: "control", nivel: "exigente",
    q: "Si ya se sabía que no era un PID, ¿por qué no se reemplazó por un PID incremental estándar?",
    r: "Se conservó porque siguió la referencia en los ensayos y porque la forma incremental simplifica la protección contra el windup. No se eligió comparando su desempeño con otras leyes. Esa comparación es el trabajo futuro 6, y por eso las ganancias informadas caracterizan esta ley y no deben leerse por su nombre.",
    donde: "Sec. 4.4.3, Anexo 4.5, Limitaciones, Trabajo futuro 6", ver: "control.html#por-que-se-conservo" },
  { id: "protocolo-formula", tema: "control", nivel: "exigente",
    q: "El protocolo serial solo transporta referencias y conteos. ¿Qué impedía reescribir la función de control sin tocar la comunicación?",
    r: "Nada lo impedía. La interfaz envía un mensaje vacío al iniciar, las referencias con el comando m y pide los encoders con el comando e. Ninguno depende de la fórmula interna, y la ley vive en un archivo separado del manejo de comandos.\n\nEl protocolo justifica conservar los comandos, no la fórmula. La ley se conservó porque siguió la referencia y por la protección contra el windup. Es un matiz que la redacción de la tesis podría precisar.",
    donde: "Sec. 4.3.3, Alg. 4.1, Tabla A4.2, Anexo 4.5", ver: "control.html#protocolo-ley" },
  { id: "windup", tema: "control", nivel: "tecnica",
    q: "¿Qué es el windup y cómo lo evita este firmware?",
    r: "El windup ocurre cuando el motor ya está al máximo y la parte integral del controlador sigue acumulando error. Cuando la situación cambia, esa acumulación tarda en descargarse y la respuesta se atrasa o se pasa.\n\nEl firmware lo evita de dos formas. Recorta la salida a 255 antes de guardarla, y solo actualiza el estado integral cuando la salida no está saturada, lo que se llama integración condicional.",
    donde: "Anexo 4.4, Åström y Hägglund Sec. 3.5", ver: "control.html#windup" },
  { id: "aporte-pso", tema: "control", nivel: "exigente",
    q: "¿Qué aportó realmente el PSO, si después del ajuste en el robot las ganancias cambiaron tanto?",
    r: "Entregó un punto de partida para las tres ganancias a la vez, calculado sobre un modelo de primer orden con retardo identificado para cada rueda, en vez de partir por tanteo. No fue el ajuste final.\n\nCon esas ganancias aparecieron un error estacionario en la rueda izquierda y una detención en la derecha, que el modelo no anticipaba porque no tiene la zona muerta del driver. Se corrigieron en el robot, subiendo Kp entre 28 y 63 %, bajando Kd entre 41 y 45 % y subiendo Ki varios órdenes de magnitud.\n\nNo se comparó contra las ganancias originales del firmware, así que no se afirma que haya ahorrado tiempo. Tampoco hubo análisis de estabilidad. Lo que se afirma es que, con las finales, el robot siguió 0,13 m/s sin sobreimpulso apreciable.",
    donde: "Sec. 4.4.5, Sec. 5.2, Tabla A4.4, Anexo 4.5", ver: "control.html#semilla" },
  { id: "lo-original", tema: "control", nivel: "tecnica",
    q: "Si el PSO no demostró ahorrar tiempo, ¿qué es lo original del procedimiento de sintonía?",
    r: "Lo propio no es el PSO por sí solo, sino el procedimiento completo. Identificar un modelo por rueda, obtener con PSO una semilla para las tres ganancias, ajustarla en el robot y documentar por qué el modelo falla, que es por la zona muerta del driver y la cuantización de los encoders. La tesis lo describe como una semilla de búsqueda y no como un ajuste validado por sí solo.",
    donde: "Justificación, Sec. 2.1, Sec. 5.2", ver: "control.html#pso" },
  { id: "resolucion", tema: "control", nivel: "exigente",
    q: "¿Cómo se informa un error de 0,002 m/s si la resolución de la medición es de 0,01 m/s? ¿Qué sobreimpulso podría quedar oculto?",
    r: "El 0,128 m/s de la rueda izquierda es el promedio de las muestras tomadas desde los 7 s. Cada muestra viene en pasos de 0,01 m/s, y al promediar valores que oscilan entre dos pasos el resultado queda entre ellos. Es un promedio, no una medición más fina.\n\nPor lo mismo, un sobreimpulso menor a un paso, cerca del 8 % de la referencia, no se alcanza a ver. Por eso se dice sin sobreimpulso apreciable dentro de la resolución de medida, y no se informa tiempo de establecimiento al 2 %.",
    donde: "Sec. 5.2, Tabla 5.3, Anexo 4.11, Tabla A4.2", ver: "control.html#resolucion" },
  { id: "un-solo-punto", tema: "control", nivel: "tecnica",
    q: "El control se evaluó solo a 0,13 m/s. ¿Qué se espera a velocidades más bajas, por ejemplo en los giros?",
    r: "Es un solo punto de operación, y por eso el OE2 es parcial. Ese valor coincide con el límite lineal del controlador diferencial y con la velocidad del ensayo de 2 m.\n\nA velocidades bajas se espera un seguimiento peor. A 0,13 m/s cada rueda cuenta unos 41 ticks por ciclo. En un giro sobre su eje a 0,35 rad/s, cada rueda va a unos 0,033 m/s, cerca de 10 ticks por ciclo. Ahí las bandas muertas de 1 y 2 ticks pesan mucho más, y el integral de la rueda izquierda casi no actúa, porque solo crece con errores de al menos 14 ticks. No se midió.",
    donde: "Tabla 4.3, Sec. 5.2, Anexo 4.4, Trabajo futuro 6", ver: "control.html#resolucion" },
  { id: "camino-orden", tema: "control", nivel: "tecnica",
    q: "¿Cómo llega una orden de velocidad desde Nav2 hasta el motor?",
    r: "Nav2 publica una velocidad lineal y una angular, con DWB pidiendo hasta 0,15 m/s. La orden pasa por twist_mux, que da prioridad al mando manual, y llega al controlador diferencial en la Raspberry. Ese controlador la limita a 0,13 m/s y 0,35 rad/s y calcula la velocidad de cada rueda.\n\nLa interfaz DiffDriveArduino la convierte a ticks por ciclo, la trunca a entero y la envía con el comando m, en un ciclo de 30 Hz. En el Arduino, cada 33 ms el controlador compara esa referencia con los ticks que contaron las interrupciones del encoder, calcula el PWM, lo limita a 255 y lo aplica al L298N. Si pasan 2 s sin órdenes, detiene los motores.\n\nDe vuelta, la Raspberry pide los conteos con el comando e y con ellos calcula la odometría.",
    donde: "Sec. 4.3.3 a 4.3.5, Alg. 4.1 y 4.2, Anexo 3.5, Tablas A3.5, A4.2 y A5.1", ver: "robot.html#camino-orden" },

  /* ── Odometría y ensayos ── */
  { id: "dos-errores", tema: "odometria", nivel: "general",
    q: "¿Qué diferencia hay entre el 7,18 % y el 3,63 %?",
    r: "Las dos cifras son del robot real y de la misma recta. Se ordenó avanzar a 0,13 m/s durante 15,4 s, el tiempo de 2 m a esa velocidad. En promedio de cinco repeticiones, los encoders estimaron 1,924 m y la cinta midió 1,856 m.\n\nEl 7,18 % es el error de seguimiento. Compara la cinta con lo ordenado y dice que el robot avanzó menos de lo pedido. Una parte ya la registran los encoders, compatible con el tiempo que tardan las ruedas en acelerar.\n\nEl 3,63 % es el error odométrico. Compara los encoders con la cinta y dice que el robot cree haber avanzado más de lo real. Su baja dispersión indica un sesgo sistemático, compatible con un error de escala en el radio de rueda o con deslizamiento, causas que no se aislaron.",
    donde: "Sec. 5.1, Tabla 5.1, Tabla A6.2", ver: "movimiento.html#recta" },
  { id: "ensayo-giro", tema: "odometria", nivel: "exigente",
    q: "El script de giro ordena 0,4 rad/s, pero el controlador limita a 0,35. ¿Qué se puede concluir de ese ensayo?",
    r: "Que tiene un error de diseño. El script pide 0,4 rad/s durante el tiempo que tomaría una vuelta a esa velocidad, pero con el límite ideal el robot llegaría a 315°. Por eso la tesis no lo llama error de odometría, sino desviación respecto de 360° nominales.\n\nTodos los giros superaron los 315° y la causa no se determinó. Los registros de cada prueba tienen la odometría, que permitiría revisar la velocidad realmente aplicada sin repetir el ensayo. La corrección es un giro controlado hasta un ángulo fijo, el trabajo futuro 8.",
    donde: "Sec. 5.1, Tabla 5.2, Anexo 6, Tablas A6.3 y A6.4", ver: "movimiento.html#giro" },
  { id: "iteracion-2", tema: "odometria", nivel: "exigente",
    q: "En una corrida el robot no se movió, pero la odometría sumó casi cuatro metros. ¿Qué pasó?",
    r: "La causa no se determinó, y así lo informa la tesis. La corrida duró 5,09 min, el explorador envió 14 metas y la odometría sumó 3,851 m, sin que el robot se moviera de su posición inicial. Es compatible con ruedas que giran sin avanzar, pero no se comprobó.\n\nLos encoders miden el giro de las ruedas y no el avance, así que solos no distinguen ese caso. El láser sí daba una señal, porque el mapa no crecía, pero el ensayo no la usa para detenerse. El explorador solo se detiene cuando no quedan fronteras, y si el robot no avanza las fronteras no se agotan.\n\nLa corrida se excluyó y se informa como falla. En las otras cinco, el crecimiento del mapa respalda el movimiento sin depender de los encoders.",
    donde: "Anexo 7, Sec. 5.4, conclusión del OE4", ver: "movimiento.html#iteracion-2" },
  { id: "datos-iteracion-2", tema: "odometria", nivel: "tecnica",
    q: "¿Qué datos se conservan de esa corrida y cómo se podría diagnosticar?",
    r: "Se conserva su registro completo, con la odometría y el flujo de estados de las 14 metas, porque la distancia de 3,851 m se calculó sobre ese registro. Lo que no se conserva es la imagen del mapa. Con el registro se puede revisar la falla sin repetir el ensayo, por ejemplo comparando la pose en el mapa con la odometría.",
    donde: "Anexo 7, Sec. 5.4", ver: "movimiento.html#iteracion-2" },
  { id: "verificador-progreso", tema: "odometria", nivel: "exigente",
    q: "Nav2 tiene un verificador de progreso que exige 5 cm cada 6 s. ¿Por qué nada detectó que el robot estaba detenido?",
    r: "El verificador compara la posición que Nav2 estima para el robot, que sale de la cadena de marcos donde slam_toolbox publica la corrección del mapa sobre la odometría. No se analizó si el verificador actuó en esa corrida, y sus 13 metas abortadas no se clasificaron, así que no se sabe si alguna terminó por el verificador o por reemplazo. Se puede revisar en el registro.",
    donde: "Tabla A5.1, Sec. 4.3.2, Anexo 7", ver: "navegacion.html#dwb" },

  /* ── Mapeo y SLAM ── */
  { id: "cierre-lazo", tema: "mapeo", nivel: "tecnica",
    q: "¿Qué es un cierre de lazo y por qué figura como no determinado?",
    r: "En el SLAM por grafos, cada nodo es una pose del robot y cada arista una restricción entre dos poses, que sale de la odometría o de alinear dos barridos del láser. Cuando el robot vuelve a ver una zona conocida, se agrega una restricción de cierre de lazo, y al optimizar el grafo el error acumulado se reparte en toda la trayectoria.\n\nEn slam_toolbox el cierre de lazo estaba activado, pero el análisis posterior no detecta automáticamente si ocurrió, y ese dato se ingresaba a mano. Por eso figura como no determinado, y la consistencia del mapa se evaluó a la vista.",
    donde: "Sec. 3.8, Fig. 3.4, Sec. 5.3, Tabla A5.3, Anexo 8.1", ver: "mapeo.html#slam" },
  { id: "por-que-slam-toolbox", tema: "mapeo", nivel: "general",
    q: "¿Por qué slam_toolbox y no otro algoritmo de SLAM?",
    r: "Por su integración nativa con ROS 2, su enfoque de grafo de poses y porque permite guardar y cargar mapas. Frente a las alternativas, GMapping no detecta cierres de lazo y su paso a ROS 2 es más débil, Hector SLAM exige un láser de alta tasa de barrido para contener la deriva, y Cartographer tiene una configuración compleja y fue el de mayor uso medio de CPU en la comparación de Trejos et al.",
    donde: "Tabla 1.2, Sec. 2.1, Sec. 4.5.1", ver: "mapeo.html#por-que-slam-toolbox" },
  { id: "trejos", tema: "mapeo", nivel: "exigente",
    q: "¿Trejos evaluó slam_toolbox? ¿Qué peso tiene el argumento de CPU si no se midió?",
    r: "No lo evaluó. Comparó Cartographer, GMapping, Hector, Karto y RTAB-Map en simulación con un TurtleBot 3 Burger simulado, y en su clasificación global Karto fue la mejor opción. slam_toolbox se construye sobre Open Karto, según sus autores.\n\nAun así, el argumento de CPU pesa poco en este caso, porque slam_toolbox corre en un computador con procesador de clase portátil y su consumo no se midió. La elección se sostiene sobre todo en la integración, el grafo de poses y el manejo de mapas.",
    donde: "Tabla 1.2, Sec. 4.5.1, Tabla A3.2, Anexo 8.3. Trejos et al. (2022), Macenski y Jambrecic (2021)", ver: "mapeo.html#por-que-slam-toolbox" },
  { id: "sesgo-y-mapa", tema: "mapeo", nivel: "tecnica",
    q: "Si la odometría tiene un sesgo de 3,63 %, ¿por qué no se acumula en el mapa?",
    r: "Porque SLAM la corrige con el láser. slam_toolbox publica esa corrección como la transformación entre el marco del mapa y el de la odometría, y la odometría solo mantiene la transformación entre su marco y el robot. Así la deriva de los encoders queda absorbida en el paso de mapa a odometría y no se acumula en el mapa.",
    donde: "Sec. 3.1, Sec. 3.8, Sec. 4.3.2. REP 105", ver: "mapeo.html#marcos" },

  /* ── Navegación ── */
  { id: "astar-dijkstra", tema: "navegacion", nivel: "general",
    q: "¿Cómo decide A estrella qué ruta tomar y qué cambia respecto de Dijkstra?",
    r: "A estrella recorre la rejilla del mapa de costos desde la posición del robot. A cada celda candidata le asigna la suma de lo que ya cuesta llegar a ella y una estimación de lo que falta hasta la meta, y siempre avanza primero por la menor suma. Esa estimación orienta la búsqueda hacia la meta y evita revisar celdas en todas direcciones, como hace Dijkstra.\n\nEn Nav2 se activa con la opción use_astar del planificador NavFn. La tesis no usa la optimalidad de la ruta como criterio, porque Nav2 agrega costos propios del mapa cuyo escalamiento no se reconstruyó. Lo que se verifica es que la ruta pueda ser seguida por el controlador local.",
    donde: "Sec. 3.10, Ec. 3.15, Tabla 4.5, Tabla A5.1", ver: "navegacion.html#astar" },
  { id: "admisible", tema: "navegacion", nivel: "tecnica",
    q: "¿Qué condición debe cumplir la estimación de A estrella para garantizar la ruta de menor costo?",
    r: "Tiene que ser admisible, es decir, nunca estimar más de lo que realmente falta. Con una estimación admisible, A estrella encuentra la ruta de menor costo en su grafo. La tesis no usa ni la admisibilidad ni la optimalidad como criterio de validación, por los costos propios que agrega Nav2.",
    donde: "Sec. 3.10", ver: "navegacion.html#astar" },
  { id: "esquina", tema: "navegacion", nivel: "exigente",
    q: "El radio de inflación es 0,15 m y la esquina del robot está a 0,24 m del centro. ¿Cómo se asegura que la ruta no pase por donde el robot no cabe?",
    r: "No se garantiza, y la tesis lo declara. Entre 0,15 y 0,24 m de un obstáculo el costo es nulo, aunque la esquina del robot pueda llegar ahí. El planificador trata al robot como un punto y el crítico de obstáculos de DWB solo revisa la celda bajo el centro, así que ninguno revisa el contorno completo.\n\nSu efecto en las corridas no se cuantificó. Evaluar la navegación en pasos estrechos con una configuración acorde es el trabajo futuro 4.",
    donde: "Sec. 4.5.4, Sec. 5.4, Anexo 5.2, Trabajo futuro 4", ver: "navegacion.html#costos" },

  /* ── Exploración ── */
  { id: "logica-explorador", tema: "exploracion", nivel: "tecnica",
    q: "¿Cuándo manda el explorador una meta nueva, y por qué aparece abortada aunque el robot no haya fallado?",
    r: "El explorador revisa el mapa de costos global cada 3,3 s, porque su frecuencia está configurada en 0,3 Hz. Busca fronteras, las ordena con un puntaje de distancia y tamaño y toma la primera que no esté en la lista negra. Si el punto elegido cambió un centímetro o más respecto de la meta anterior, manda una meta nueva sin cancelar la que está en curso.\n\nEn la versión Foxy de Nav2, cuando llega una meta nueva mientras otra está activa, la anterior se cierra como abortada. Por eso el aborto registra reemplazos y no fallas.\n\nEl efecto extra es que el explorador agrega a la lista negra toda meta abortada, incluso las que él mismo reemplazó. La solución es cancelar la meta antes de enviar la siguiente, el trabajo futuro 5.",
    donde: "Sec. 4.5.6, Alg. 4.4, Sec. 5.4, Tabla A5.4, Anexos 5.6 y 8.4", ver: "exploracion.html#explore-lite" },
  { id: "por-que-no-corrigio", tema: "exploracion", nivel: "exigente",
    q: "Si el reemplazo de metas explica casi todos los abortos, ¿por qué no se corrigió antes de los ensayos?",
    r: "Porque se detectó después, al reconstruir cada meta por su identificador. Los contadores automáticos de la sesión contaban mensajes de estado y no metas, así que el problema no era visible en los resúmenes. Corregirlo exige cancelar la meta en curso antes de enviar la siguiente, o conservar el registro del navegador, y evaluar el efecto de la frecuencia del explorador.",
    donde: "Limitaciones, Anexo 8.4, Trabajo futuro 5", ver: "exploracion.html#medir-bien" },
  { id: "yamauchi", tema: "exploracion", nivel: "tecnica",
    q: "¿Qué criterio propone Yamauchi para elegir frontera, y en qué se diferencia del explorador usado?",
    r: "Yamauchi propone ir a la frontera accesible más cercana que no se haya visitado. Al llegar, el robot hace un barrido de 360°, actualiza el mapa y vuelve a buscar. Si no logra avanzar en cierto tiempo, marca esa frontera como inaccesible.\n\nEl explorador usado toma la idea general, los bordes entre lo conocido y lo desconocido, y una lista de metas descartadas equivalente. Cambia en tres cosas. Elige con un puntaje de distancia y tamaño, vuelve a elegir cada 3,3 s sin esperar a llegar, y acepta fronteras mucho más pequeñas, porque Yamauchi exige un tamaño parecido al del robot. La segunda diferencia explica los 53 reemplazos.",
    donde: "Yamauchi (1997), secciones 2.2 y 2.3. Sec. 1.4.2, Sec. 3.11, Tabla A5.4, Anexo 5.6", ver: "exploracion.html#explore-lite" },
  { id: "frontera-minima", tema: "exploracion", nivel: "exigente",
    q: "Con un tamaño mínimo de frontera de 5 cm, una sola celda, ¿qué consecuencia hay sobre las metas?",
    r: "El archivo de ejemplo del paquete trae 0,75 m. Con 0,05 m y celdas de 5 cm, se aceptan fronteras de una sola celda. El explorador puede entonces elegir fronteras muy pequeñas, que pueden venir del ruido del láser o de rincones donde el robot no cabe, lo que puede alargar la exploración y llenar la lista negra. No se cuantificó. Yamauchi usa un tamaño cercano al del robot justamente para descartar esas regiones.",
    donde: "Tabla A5.4, Anexo 5.6. Yamauchi (1997), sección 2.2", ver: "exploracion.html#dos-fronteras" },

  /* ── Gemelo digital ── */
  { id: "criterio-oe1", tema: "gemelo", nivel: "tecnica",
    q: "¿Con qué criterio se da por cumplido el OE1, y qué evidencia hay de que simulación y robot se comportan igual?",
    r: "El OE1 se cumplió con una verificación de funcionamiento, no con números. En Gazebo se comprobaron los cuatro criterios de la Tabla A2.2. Cadena de marcos completa, láser y odometría publicándose de forma estable, movimiento coherente con el modelo diferencial, y radio y separación de ruedas iguales a los del prototipo.\n\nEso muestra que el gemelo reproduce marcos, sensores y movimientos, pero no reemplaza una medición. No hay una comparación sobre una misma variable, porque la pose verdadera de Gazebo no quedó registrada. Registrarla es el trabajo futuro 9.",
    donde: "Tabla A2.2, Sec. 4.2.4, Sec. 5.5, conclusión del OE1", ver: "gemelo.html#criterios" },
  { id: "registro-gemelo", tema: "gemelo", nivel: "exigente",
    q: "¿Dónde quedó registrado lo observado en el gemelo, por ejemplo la frecuencia medida del láser y de la odometría?",
    r: "No quedó registrado. La tesis dice que los criterios se confirmaron durante la puesta en marcha del modelo, pero no se guardaron los valores medidos ni la imagen del árbol de marcos. Es una debilidad del registro, que se corrige agregando esas mediciones al anexo.",
    donde: "Anexo 2.2", ver: "gemelo.html#criterios" },
  { id: "rviz-o-gazebo", tema: "gemelo", nivel: "general",
    q: "Una imagen de RViz junto a una cámara cenital, ¿es simulación o robot real?",
    r: "Es el robot real. RViz es el programa donde se ven los datos que envía el robot, con el mapa y la ruta planificada en verde. Puede mostrar datos del simulador o del robot, pero las capturas junto a la cámara cenital son del robot real. Las capturas de simulación son de Gazebo Classic.",
    donde: "Fig. 4.2, Fig. 4.3, Fig. 5.5, Fig. A7.1", ver: "mapeo.html#como-crece" },
  { id: "sim-vs-real", tema: "gemelo", nivel: "exigente",
    q: "¿El 3,39 % de simulación y el 7,18 % del robot miden lo mismo?",
    r: "No. En la recta de 2 m, en simulación la distancia sale de la propia odometría, porque la pose verdadera de Gazebo no quedó registrada, y da 3,39 % frente a lo ordenado. En el robot se mide con cinta métrica y da 7,18 %. Una se mide consigo misma y la otra contra una referencia física.\n\nEn el giro, los dos entornos se comparan con 360° nominales, 4,74 % en simulación y 3,24 % en el robot, y eso no mide error de odometría. Por eso no se comparan números entre entornos.",
    donde: "Tabla 5.1, Sec. 5.1, Tabla 5.2, Sec. 5.5", ver: "gemelo.html#no-se-comparan" },
  { id: "video-prueba", tema: "gemelo", nivel: "tecnica",
    q: "¿Qué demuestra un video donde se ven en paralelo la simulación y el robot real?",
    r: "Muestra al sistema funcionando, pero no reemplaza una medición ni compara una misma variable. La evidencia del OE1 son los criterios de la Tabla A2.2, y la tesis declara que no se comparó una misma variable entre ambos entornos. Además, el mundo simulado no es el recinto real.",
    donde: "Sec. 5.5, Tabla A2.2", ver: "resultados.html#video" },

  /* ── Decisiones de diseño ── */
  { id: "foxy", tema: "decisiones", nivel: "exigente",
    q: "Si ROS 1 se descartó por estar sin soporte, ¿no es contradictorio usar ROS 2 Foxy y Gazebo Classic, que también lo están?",
    r: "Es una contradicción aparente. ROS 2 se eligió por su arquitectura distribuida sin maestro central y por el ecosistema de Nav2, no por el soporte, y la tesis aclara que el fin de soporte de ROS 1 no fue criterio, justamente porque Foxy también está fuera de soporte.\n\nFoxy, Ubuntu 20.04 y Gazebo Classic se congelaron al inicio para asegurar que toda la cadena de paquetes funcionara con el hardware. Migrar a mitad del proyecto obligaba a rehacer y volver a probar todo. El fin de vida es una limitación declarada y la migración es el trabajo futuro 3.",
    donde: "Alcances y limitaciones, Sec. 1.5, Sec. 2.1, Limitaciones, Tabla A3.2", ver: "problema.html#decisiones" },
  { id: "sin-computador", tema: "decisiones", nivel: "general",
    q: "¿El robot podría explorar solo, sin el computador?",
    r: "No. Es una arquitectura distribuida. En el robot va lo rápido y crítico. El Arduino lee los encoders y controla cada rueda, y si deja de recibir órdenes detiene los motores. La Raspberry corre la interfaz con ros2_control, calcula la odometría y lee el láser. En el computador va lo que exige más cálculo, el mapeo con slam_toolbox, la navegación con Nav2 y el explorador. ROS 2 no tiene un maestro central, y los dos equipos se comunican por una red Wi-Fi dedicada.",
    donde: "Sec. 1.1, Sec. 3.2, Cap. 2, Fig. 2.1, Anexo 3.1", ver: "robot.html#arquitectura" },
  { id: "red", tema: "decisiones", nivel: "tecnica",
    q: "¿Cómo es la red entre el robot y el computador, y pudo afectar los ensayos?",
    r: "Es una red Wi-Fi dedicada, armada con un router de viaje y direcciones IP fijas, así que el tráfico va por la red local de ese router. Una red lenta puede retrasar órdenes, pero no puede explicar que los encoders sumen distancia, porque la odometría se calcula en la Raspberry con sus propios conteos.",
    donde: "Anexo 3.1, Tabla A1.1", ver: "robot.html#ros2" },
  { id: "comprar-o-construir", tema: "decisiones", nivel: "general",
    q: "¿Por qué construir este robot en vez de comprar un TurtleBot 3 Burger?",
    r: "No porque ofrezca lo mismo más barato. El Burger trae unidad inercial y actuadores con controlador integrado. El robot costó un 32 % menos y el proyecto completo un 11 % menos, con precios del Burger de catálogo, sin envío ni impuestos.\n\nLo que se gana es poder documentar y modificar cada capa, desde el firmware hasta la exploración. Dos ejemplos concretos son el hallazgo de que la ley llamada PID opera como PI incremental y el programa propio para leer el láser.",
    donde: "Justificación, Anexo 1.2, Tabla A1.2, Anexos 3.4 y 4.5", ver: "robot.html#costo" },

  /* ── Para todo público ── */
  { id: "explicar-simple", tema: "publico", nivel: "general",
    q: "¿Qué hace este robot, explicado sin tecnicismos, y dónde podría servir?",
    r: "Es un robot que entra a un espacio interior que no conoce, decide solo hacia dónde avanzar y va dibujando el plano del lugar hasta que no le queda nada nuevo por mirar. Es un prototipo, no un producto, y el cálculo pesado lo hace un computador que se comunica con él por red.\n\nSirve para docencia e investigación, y la misma idea la usan robots de inspección y de logística en interiores. Se probó en un recinto pequeño, así que el paso siguiente es un espacio mayor.",
    donde: "Sec. 1.1, Limitaciones", ver: "index.html" },
  { id: "costo", tema: "publico", nivel: "general",
    q: "¿Cuánto costó el robot, y ese monto incluye todo lo necesario para que funcione?",
    r: "Los materiales montados en el robot costaron 444 643 pesos. El proyecto completo llega a 582 447, porque suma el router de viaje, los cables de red, el cargador, las baterías de repuesto y los accesorios de desarrollo.\n\nNingún monto incluye el computador, que es necesario porque ahí corren el mapeo, la navegación y el explorador. Por eso el bajo costo se refiere a lo que va en el robot.",
    donde: "Sec. 4.1, Tabla A1.1, Anexo 1.2", ver: "robot.html#costo" },
  { id: "oficina", tema: "publico", nivel: "general",
    q: "Si se lleva el robot a una oficina con sillas, mesas, ventanales y gente caminando, ¿dónde fallaría?",
    r: "El láser mide en un solo plano horizontal, así que no ve lo que queda por encima o por debajo, como la cubierta de una mesa o el asiento de una silla. Se degrada con superficies muy reflectantes, como el vidrio, o muy absorbentes. No está pensado para obstáculos rápidos ni suelos irregulares, y la odometría deriva en recorridos largos porque no hay unidad inercial. Y en pasos estrechos la configuración no garantiza espacio para la esquina del robot.",
    donde: "Sec. 3.3.1, Alcances y limitaciones, Limitaciones, Anexo 5.2", ver: "resultados.html#donde-fallaria" },
  { id: "espacio-grande", tema: "publico", nivel: "tecnica",
    q: "Si el espacio fuera treinta veces más grande, ¿qué impide asegurar que lo exploraría completo?",
    r: "No se puede asegurar. Se probó un único recinto, con 3,50 m² de área libre media, y cinco corridas de una misma sesión. En un espacio grande la odometría acumula más deriva sin unidad inercial, y no se midieron la autonomía de la batería ni el uso del computador.\n\nAdemás, el mapa de costos global del robot es una ventana de 10 por 10 m que se mueve con él, y el explorador busca fronteras en ese mapa, así que en un espacio mayor habría que revisar que no dé por terminada la exploración antes de tiempo.",
    donde: "Limitaciones, Anexo 8.3, Trabajos futuros 1, 2 y 4", ver: "navegacion.html#costos" }
];
